#!/bin/bash
# axe-linter pre-commit
# This script will setup the environment variables needed for the axe-linter-connector
# and execute the axe-linter-connector. The output file will be reviewed and call back with exit codes:
## 0 - No Accessibility Defects
## 1 - axe-linter Detected Accessibility Defects
## 2 - Execution problem, or Axe-Linter Server unavailable.
 
echo "axe-linter Starting $(date)"
 
# Setup variables for axe-linter Server
StatusCode=0
 
# Configure verbose output.
VerboseOutput="false"
# Configure outfile: output in Generic Issue Import Format for in execution directory.
OutFile="axe-linter-report.json"
 
for i in $(git status --porcelain | sed s/^...//); do
   TempStatus=0
shopt -s nocasematch;
        if [[ $i == *.html ]] || [[ $i == *.js ]] || [[ $i == *.jsx ]]|| [[ $i == *.ts ]]|| [[ $i == *.tsx ]]|| [[ $i == *.vue ]]|| [[ $i == *.htm ]]|| [[ $i == *.md ]]|| [[ $i == *.markdown ]];
#if [[ $i == *.html ]];
        then
           if $VerboseOutput; then
        echo "Accessibility check: file: $i"
            fi
        # execute axe-linter connector
        axe-linter-connector -s $i -d . -u https://axe-linter.deque.com --api-key AXE_LINTER_API_KEY
 
        if [ ! -f "$OutFile" ];
           then
             echo "$OutFile Does Not Exit"
             exit 2
 
           elif cat "$OutFile" | grep -q "BUG"; then
              if $VerboseOutput; then
              cat $OutFile
              fi
              echo "**axe-linter Accessibility Issues Detected: $i"
              TempCode=1
           else
             echo "No axe-linter Connector Issues Detected in: $i"
        fi
           if (($TempCode != 0))
           then
            StatusCode=1
          fi
        rm $OutFile
        fi
done
 
if (($StatusCode !=0))
        then
        echo "Commit Failed due to Accessibility Issues"
        fi
exit $StatusCode